services:
  - type: web
    name: recibos-ipmr
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /admin
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: SESSION_SECRET
        generateValue: true
      - key: MAIL_TO
        value: juantony794@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: ADMIN_PASSWORD
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    disk:
      name: datos
      mountPath: /var/data
      sizeGB: 1
